### ISSUE TITLE
THIS NOT A QUICKSHOP FAULT

### ISSUE THREAD

**Issue by Chypik** [iconomy5legacy/iConomy#27]
Paper-354 (MC: 1.17.1)
QuickShop v5.0.0.17-SNAPSHOT
Vault v1.7.3-b131
iConomy v5.13

```
[18:45:17] [Server thread/WARN]: [QuickShop] QuickShop received an error when processing Economy response, THIS NOT A QUICKSHOP FAULT, you might need ask help with your Economy Provider plugin (iConomy 5.13) author.
java.lang.NullPointerException: Cannot invoke "com.iConomy.system.Account.getHoldings()" because the return value of "com.iConomy.iConomy.getAccount(String)" is null
	at com.iConomy.util.VaultConnector.depositPlayer(VaultConnector.java:119) ~[iConomy-5.13.jar:?]
	at org.maxgamer.quickshop.economy.Economy_Vault.deposit(Economy_Vault.java:142) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:190) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.commit(EconomyTransaction.java:142) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.maxgamer.quickshop.api.economy.EconomyTransaction.failSafeCommit(EconomyTransaction.java:129) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.actionSell(SimpleShopManager.java:1077) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.actionTrade(SimpleShopManager.java:1440) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.maxgamer.quickshop.shop.SimpleShopManager.lambda$handleChat$4(SimpleShopManager.java:490) ~[QuickShop-5.0.0.17-SNAPSHOT_2011.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-354]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-354]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[patched_1.17.1.jar:git-Paper-354]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-354]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-354]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-354]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-354]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

```

**Comment by LlmDl** [comment]
Any thoughts on what the account name is?

**Comment by Chypik** [comment]
such an error occurs when buying in any store, even from the player, even in the admin shop. There is a suspicion that the economy plug-in does not see the player who buys the product, but the money is debited

**Comment by LlmDl** [comment]
iConomy says those people/things do not have accounts.
