### ISSUE TITLE
Could not pass event InventoryCloseEvent to ChestShop

### ISSUE THREAD

**Issue by ewof** [iconomy5legacy/iConomy#40]
```


[21:53:24 ERROR]: Could not pass event InventoryCloseEvent to ChestShop v3.12.3-SNAPSHOT (build 388)
java.lang.NullPointerException: Cannot read field "captureTreeGeneration" because the return value of "net.minecraft.world.level.World.getCurrentWorldData()" is
null
        at net.minecraft.world.level.Level.getBlockState(Level.java:811) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at com.Acrobot.ChestShop.Utils.uBlock.couldBeShopContainer(uBlock.java:316) ~[ChestShop.jar:?]
        at com.Acrobot.ChestShop.Listeners.Modules.StockCounterModule.onInventoryClose(StockCounterModule.java:69) ~[ChestShop.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[folia-api-1.20.1-R0.1-SNAPSH
OT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:git-Folia-"6b978f2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1584) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at net.minecraft.server.level.ServerPlayer.closeContainer(ServerPlayer.java:2031) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:573) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at nl.pim16aap2.bigDoors.GUI.GUI.close(GUI.java:591) ~[BigDoors.jar:?]
        at nl.pim16aap2.bigDoors.handlers.GUIHandler$1.run(GUIHandler.java:52) ~[BigDoors.jar:?]
        at >nl.pim16aap2.bigDoors.lib.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58) ~[BigDoors.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:178) ~[folia-1.20.1.jar:
?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:36) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"6b978f2"
]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:53:25 ERROR]: Could not pass event InventoryCloseEvent to ChestShop v3.12.3-SNAPSHOT (build 388)
java.lang.NullPointerException: null


```
i used with [bigdoors](https://github.com/Anon8281/BigDoors) but i dont think it's related to bigdoors because it just fires the event
i'm on folia 1.20.1

**Comment by LlmDl** [comment]
Did you get the correct repo here? I don't think this has to do with iConomy.

**Comment by ewof** [comment]
bro i am so sorry lol i have like 100 tabs open rn
